// AUTO-GENERATED by tools/gen-index.mjs — do not edit by hand.
import s0 from './anthropic_court.js';
import s1 from './anthropic_garden.js';
import s2 from './anthropic_gate.js';
import s3 from './anthropic_hall.js';
import s4 from './anthropic_library.js';
import s5 from './bunker_corridor.js';
import s6 from './cafe_backroom.js';
import s7 from './cafe_basement.js';
import s8 from './cafe_main.js';
import s9 from './fable_core.js';
import s10 from './fable_finale.js';
import s11 from './google_corridors.js';
import s12 from './google_graveyard.js';
import s13 from './google_kitchen.js';
import s14 from './google_lobby.js';
import s15 from './google_meeting.js';
import s16 from './junction.js';
import s17 from './openai_boardroom.js';
import s18 from './openai_corridor.js';
import s19 from './openai_expo.js';
import s20 from './openai_lobby.js';
import s21 from './openai_stage.js';
import s22 from './street.js';
import s23 from './xai_gate.js';
import s24 from './xai_hangar.js';
import s25 from './xai_junkyard.js';
import s26 from './xai_meme_engine.js';
import s27 from './xai_truck.js';

export const SCENES = {
  'anthropic_court': s0,
  'anthropic_garden': s1,
  'anthropic_gate': s2,
  'anthropic_hall': s3,
  'anthropic_library': s4,
  'bunker_corridor': s5,
  'cafe_backroom': s6,
  'cafe_basement': s7,
  'cafe_main': s8,
  'fable_core': s9,
  'fable_finale': s10,
  'google_corridors': s11,
  'google_graveyard': s12,
  'google_kitchen': s13,
  'google_lobby': s14,
  'google_meeting': s15,
  'junction': s16,
  'openai_boardroom': s17,
  'openai_corridor': s18,
  'openai_expo': s19,
  'openai_lobby': s20,
  'openai_stage': s21,
  'street': s22,
  'xai_gate': s23,
  'xai_hangar': s24,
  'xai_junkyard': s25,
  'xai_meme_engine': s26,
  'xai_truck': s27,
};
export const START_ROOM = 'cafe_main';
export const MAX_SCORE = 500;
export const GAME_TITLE = "פייבל 5: זהירות, רצפה רטובה";
