#!/usr/bin/env node
// Generate js/scenes/index.js from all scene files (js/scenes/*.js, excluding *.art.js, index.js, _*).
// Reads game meta from story/manifest.json: { title, startRoom, maxScore }
import { readdirSync, writeFileSync, readFileSync, existsSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const dir = `${ROOT}/js/scenes`;
const ids = readdirSync(dir)
  .filter(f => f.endsWith('.js') && !f.endsWith('.art.js') && f !== 'index.js' && !f.startsWith('_'))
  .map(f => f.replace(/\.js$/, ''))
  .sort();

let meta = { title: 'FABLE QUEST: מלחמות הבינה', startRoom: ids[0], maxScore: 500 };
const mf = `${ROOT}/story/manifest.json`;
if (existsSync(mf)) {
  const m = JSON.parse(readFileSync(mf, 'utf8'));
  meta.title = m.title || meta.title;
  meta.startRoom = m.startRoom || meta.startRoom;
  meta.maxScore = m.maxScore || meta.maxScore;
}
if (!ids.includes(meta.startRoom)) {
  console.error(`⚠ startRoom "${meta.startRoom}" not among scenes; falling back to ${ids[0]}`);
  meta.startRoom = ids[0];
}

const lines = [
  '// AUTO-GENERATED by tools/gen-index.mjs — do not edit by hand.',
  ...ids.map((id, i) => `import s${i} from './${id}.js';`),
  '',
  'export const SCENES = {',
  ...ids.map((id, i) => `  '${id}': s${i},`),
  '};',
  `export const START_ROOM = '${meta.startRoom}';`,
  `export const MAX_SCORE = ${meta.maxScore};`,
  `export const GAME_TITLE = ${JSON.stringify(meta.title)};`,
  '',
];
writeFileSync(`${dir}/index.js`, lines.join('\n'));
console.log(`✓ generated index.js with ${ids.length} scenes, start=${meta.startRoom}, maxScore=${meta.maxScore}`);
